### PR TITLE
using Promise.all to replace forloop

### PR DESCRIPTION
**Pull request by midnightcodr**

### CODE REVIEW

**Comment by Marsup** [comment]
What's the motivation ? Are you establishing that many connections ?

**Comment by midnightcodr** [comment]
My motivation is this https://gist.github.com/midnightcodr/9d1b6d919d7e149acec95e15ceb53d00

**Comment by midnightcodr** [comment]
I do understand your question. If things can be done in parallel, why not.

**Comment by midnightcodr** [comment]
Awesome! Thank you!

**Pull request merged**
